# Generated by Django 5.1.2 on 2026-03-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_opportunity_is_noncompetitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='project_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='project_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
