# Generated by Django 5.1.2 on 2026-04-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_opportunity_project_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opp_type',
            field=models.CharField(choices=[('EOI', 'EOI'), ('RFP', 'RFP'), ('FC', 'Fore-cast'), ('NA', 'Not Applicable')], max_length=3),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.IntegerField(choices=[(1, 'Entered'), (2, 'Go'), (3, 'NO-Go'), (4, 'Consider'), (5, 'Submitted'), (6, 'Lost'), (7, 'Won'), (8, 'Cancelled'), (9, 'Assumed Lost'), (10, 'N/A'), (11, 'Transfer to RFP'), (12, 'On going'), (11, 'Finished')], default=1),
        ),
    ]
