# Generated by Django 5.1.2 on 2026-04-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_opportunity_opp_type_alter_opportunity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.IntegerField(choices=[(1, 'Entered'), (2, 'Go'), (3, 'NO-Go'), (4, 'Consider'), (5, 'Submitted'), (6, 'Lost'), (7, 'Won'), (8, 'Cancelled'), (9, 'Assumed Lost'), (10, 'N/A'), (11, 'Transfer to RFP'), (12, 'On going'), (13, 'Finished')], default=1),
        ),
    ]
