# Generated by Django 5.1.2 on 2026-05-07 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_opportunity_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['code'], 'verbose_name_plural': 'currencies'},
        ),
        migrations.AlterModelOptions(
            name='institute',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name']},
        ),
    ]
