# Generated by Django 5.1.2 on 2026-05-10 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_currency_options_alter_institute_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'go_reason',
            },
        ),
        migrations.CreateModel(
            name='NoGoReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nogo_reason',
            },
        ),
        migrations.CreateModel(
            name='OpportunityGoReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('other_reason_description', models.CharField(blank=True, max_length=255, null=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.opportunity')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.goreason')),
            ],
            options={
                'db_table': 'opportunity_go_reason',
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='go_reasons',
            field=models.ManyToManyField(related_name='opportunity_go_reason', through='tracker.OpportunityGoReason', to='tracker.goreason'),
        ),
        migrations.CreateModel(
            name='OpportunityNoGoReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('other_reason_description', models.CharField(blank=True, max_length=255, null=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.opportunity')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.nogoreason')),
            ],
            options={
                'db_table': 'opportunity_nogo_reason',
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nogo_reasons',
            field=models.ManyToManyField(related_name='opportunity_nogo_reason', through='tracker.OpportunityNoGoReason', to='tracker.nogoreason'),
        ),
        migrations.AddConstraint(
            model_name='opportunitygoreason',
            constraint=models.UniqueConstraint(fields=('opportunity', 'reason'), name='unique_opportunity_go_reason'),
        ),
        migrations.AddConstraint(
            model_name='opportunitynogoreason',
            constraint=models.UniqueConstraint(fields=('opportunity', 'reason'), name='unique_opportunity_nogo_reason'),
        ),
    ]
