# Generated by Django 5.1.2 on 2026-05-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_goreason_nogoreason_opportunitygoreason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='go_reasons',
            field=models.ManyToManyField(blank=True, null=True, related_name='opportunity_go_reason', through='tracker.OpportunityGoReason', to='tracker.goreason'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='nogo_reasons',
            field=models.ManyToManyField(blank=True, null=True, related_name='opportunity_nogo_reason', through='tracker.OpportunityNoGoReason', to='tracker.nogoreason'),
        ),
    ]
