# Generated by Django 5.1.2 on 2026-05-19 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_opportunity_go_reasons_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
    ]
