# Generated by Django 5.1.2 on 2026-05-19 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_alter_country_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Budget Template',
                'verbose_name_plural': 'Budget Templates',
                'db_table': 'budget_template',
            },
        ),
        migrations.CreateModel(
            name='BudgetTemplateColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('display_order', models.PositiveBigIntegerField(default=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='tracker.budgettemplate')),
            ],
            options={
                'verbose_name': 'Budget Template Column',
                'verbose_name_plural': 'Budget Templates Columns',
                'db_table': 'budget_template_column',
                'ordering': ['display_order'],
                'unique_together': {('template', 'key')},
            },
        ),
        migrations.CreateModel(
            name='BudgetTemplateRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('row_type', models.CharField(choices=[('input', 'Input'), ('total', 'Total')], default='input', max_length=20)),
                ('display_order', models.PositiveBigIntegerField(default=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='tracker.budgettemplate')),
            ],
            options={
                'verbose_name': 'Budget Template Row',
                'verbose_name_plural': 'Budget Template Rows',
                'db_table': 'budget_template_row',
                'ordering': ['display_order'],
                'unique_together': {('template', 'key')},
            },
        ),
    ]
