# Generated by Django 5.1.2 on 2026-05-19 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_budgettemplate_budgettemplatecolumn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_rate_to_default_cur', models.DecimalField(decimal_places=6, max_digits=12)),
                ('Opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='tracker.opportunity')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_budget', to='tracker.budgettemplate')),
            ],
            options={
                'db_table': 'opportunity_budget',
            },
        ),
    ]
