# Generated by Django 5.1.2 on 2026-05-19 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_opportunitybudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityBudgetValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='tracker.opportunitybudget')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_values', to='tracker.budgettemplatecolumn')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_values', to='tracker.budgettemplaterow')),
            ],
            options={
                'db_table': 'budget_value',
                'unique_together': {('budget', 'row', 'column')},
            },
        ),
    ]
