# Generated by Django 5.1.2 on 2026-05-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_opportunitybudgetvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgettemplaterow',
            name='row_type',
            field=models.CharField(choices=[('input', 'Input'), ('display', 'Display'), ('total', 'Total')], default='input', max_length=20),
        ),
    ]
