# Generated by Django 5.1.2 on 2026-05-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_alter_budgettemplaterow_row_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgettemplatecolumn',
            name='is_readonly',
            field=models.BooleanField(default=False),
        ),
    ]
