# Generated by Django 5.1.2 on 2026-05-21 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_budgettemplatecolumn_is_readonly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunitybudget',
            old_name='Opportunity',
            new_name='opportunity',
        ),
    ]
