# Generated by Django 5.1.2 on 2026-08-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_rename_opportunity_opportunitybudget_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
