# Generated by Django 5.1.2 on 2026-08-15 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_currency_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitybudget',
            name='ex_currency',
            field=models.ForeignKey(default='CHF', on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_budget', to='tracker.currency'),
        ),
    ]
