# Generated by Django 5.1.2 on 2026-08-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_opportunitybudget_ex_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opp_type',
            field=models.CharField(choices=[('EOI', 'EOI'), ('RFP', 'RFP'), ('FC', 'Fore-cast'), ('NA', 'Not Applicable'), ('FA', 'Framework Agreement')], max_length=3),
        ),
    ]
