# Generated by Django 5.1.2 on 2026-08-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_alter_opportunity_opp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingagency',
            name='agency_type',
            field=models.CharField(blank=True, choices=[('BDA', 'Bilateral'), ('C', 'Corporate'), ('F', 'Foundation'), ('GF', 'Global Financing'), ('NGO', 'NGO'), ('UN', 'UN')], max_length=3, null=True),
        ),
    ]
