# Generated by Django 5.1.2 on 2026-08-26 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_fundingagency_agency_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institute',
            options={'ordering': ['name'], 'verbose_name': 'Partner Institute'},
        ),
        migrations.AlterField(
            model_name='opportunitybudget',
            name='ex_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_budget', to='tracker.currency'),
        ),
    ]
